version: '3.7'

services:
  cabinet:
    container_name: car_sharing
    image: postgres:latest
    hostname: localhost
    ports:
      - 5433:5432
    env_file:
      - .env
    restart: unless-stopped
